name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag dexterquazi/testtask
    - name: Auth
      run: echo ${{ secrets.DOCKER_PASS }} login docker.io -u dexterquazi --password-stdin 
    - name: push
      run: docker push dexterquazi/testtask
    
    
